[package]
edition = "2021"
name = "token-factory"
version = "0.1.0"

[dependencies]
candid = "0.7"
common = { path = "../common" }
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
ic-kit = { git = "https://github.com/infinity-swap/ic-kit" }
# ic-storage = {git = "https://github.com/infinity-swap/ic-helpers.git", package = "ic-storage"}
# ic-helpers = {git = "https://github.com/infinity-swap/ic-helpers.git", package = "ic-helpers"}
# ic-canister = { git = "https://github.com/infinity-swap/ic-helpers.git", package = "ic-canister" }
ic-canister = { path = "../../ic-helpers/ic-canister/ic-canister" }
ic-helpers = { path = "../../ic-helpers/ic-helpers" }
ic-storage = { path = "../../ic-helpers/ic-storage" }
serde = "1.0"
ic-types = {git = "https://github.com/infinity-swap/ic"}
ledger-canister = {git = "https://github.com/infinity-swap/ic"}
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
