[package]
edition = "2021"
name = "token-factory"
version = "0.24.0"

[features]
default = []
export-api = ["canister-sdk/factory-api", "canister-sdk/metrics-api"]

[dependencies]
candid = "0.8"
serde = "1.0"
thiserror = "1.0"
canister-sdk = { git = "https://github.com/infinity-swap/canister-sdk", package = "canister-sdk", branch = "stable_storage", features = ["factory"] }
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", branch = "stable_storage" }

token = { path = "../token/api", package = "is20-token" }
