[package]
edition = "2021"
name = "factory"
version = "0.1.0"

[dependencies]
candid = "0.7"
common = {path = "../common"}
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
ic-helpers = {git = "https://github.com/infinity-swap/ic-helpers.git", package = "ic-helpers", branch = "main"}
serde = "1.0"
ic-storage = {git = "https://github.com/infinity-swap/ic-helpers.git", package = "ic-storage"}
ic-types = {git = "https://github.com/infinity-swap/ic"}
ledger-canister = {git = "https://github.com/infinity-swap/ic"}
thiserror = "1.0"
