[package]
edition = "2021"
name = "token-factory"
version = "0.1.2"

[features]
default = []
no_api = []

[dependencies]
candid = "0.7"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
ic-canister = { git = "https://github.com/infinity-swap/ic-helpers", package = "ic-canister", tag = "v0.3.4" }
ic-helpers = { git = "https://github.com/infinity-swap/ic-helpers", package = "ic-helpers", tag = "v0.3.4" }
ic-storage = { git = "https://github.com/infinity-swap/ic-helpers", package = "ic-storage", tag = "v0.3.4" }
token = { path = "../token", features = ["no_api"] }
serde = "1.0"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
