[package]
edition = "2021"
name = "token-factory"
version = "0.1.6"

[features]
default = []
no_api = []

[dependencies]
candid = "0.7"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", branch = "awkure/pre-update-hook" }
ic-helpers = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-helpers", branch = "awkure/pre-update-hook" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", branch = "awkure/pre-update-hook" }
ic-factory = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-factory", branch = "awkure/pre-update-hook" }
# ic-canister = { path = "../../../ic-helpers/ic-canister/ic-canister" }
# ic-helpers = { path = "../../../ic-helpers/ic-helpers" }
# ic-storage = { path = "../../../ic-helpers/ic-storage" }
# ic-factory = { path = "../../../ic-helpers/ic-factory" }
serde = "1.0"
thiserror = "1.0"
token = { path = "../token/api", features = ["no_api"], package = "token-api" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
