[package]
edition = "2021"
name = "is20-token-canister"
version = "0.2.0"

[features]
default = []
export_api = ["token-api/export_api"]

[dependencies]
candid = "0.7"
serde = "1.0"
<<<<<<< HEAD
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", tag = "v0.3.20-dev" }
ic-helpers = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-helpers", tag = "v0.3.20-dev" }
ic-storage = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-storage", tag = "v0.3.20-dev" }
ic-auction = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-auction", tag = "v0.3.20-dev" }
ic-certified-map = "0.3"
=======
canister-sdk = { git = "https://github.com/infinity-swap/canister-sdk", package = "canister-sdk", tag = "v0.3.21", features = ["auction"] }
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", tag = "v0.3.21" }
>>>>>>> 283b773702b905eb89bbe063cb2c3efcb15cfc5e
token-api = { path = "../api", package = "is20-token", features = ["auction", "claim"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-std = {version = "1.10.0", features = ["attributes"]}

[dev-dependencies]
coverage-helper = "0.1"
